#pragma once

#include <cstdint>
#include <cstring>
#include <vector>
#include <deque>
#include <unordered_map>
#include <unordered_set>
#include <mutex>
#include <string>
#include <openssl/hmac.h>
#include <openssl/evp.h>
#include <openssl/crypto.h>

// FIX CRIT-5: Upper bounds for pre-authentication state to prevent DoS
// via handshake flooding. Values chosen to allow legitimate burst traffic
// while capping memory: 1024 * ~40 bytes ≈ 40KB for pending_clients,
// 100000 * 8 bytes ≈ 800KB for seen_timestamps.
static constexpr size_t MAX_PENDING_CLIENTS = 1024;
static constexpr size_t MAX_SEEN_TIMESTAMPS = 100000;
static constexpr uint64_t PENDING_CLIENT_TTL_MS = 30000; // 30 seconds

struct SessionKeys {
    uint8_t send_key[32];
    uint8_t recv_key[32];
    uint64_t session_id;
    uint32_t assigned_ip;
    uint16_t mtu;
};

// Forward declaration for OpenSSL EVP_PKEY
struct evp_pkey_st;
typedef struct evp_pkey_st EVP_PKEY;


// ==============================================================================
// Stateless Handshake Cookie Generator & Validator (WireGuard / DTLS 1.3 style)
// Defends server memory against UDP handshake spoofing & state exhaustion attacks
// ==============================================================================
class StatelessCookie {
public:
    static constexpr size_t COOKIE_LEN = 16;

    static inline void generate(const uint8_t secret[32], uint32_t client_ip, uint16_t client_port, uint64_t now_sec, uint8_t cookie_out[16]) noexcept {
        uint64_t epoch = now_sec / 20;
        uint8_t msg[14];
        std::memcpy(msg, &client_ip, 4);
        std::memcpy(msg + 4, &client_port, 2);
        std::memcpy(msg + 6, &epoch, 8);

        unsigned int md_len = 0;
        uint8_t md[EVP_MAX_MD_SIZE];
        HMAC(EVP_sha256(), secret, 32, msg, sizeof(msg), md, &md_len);
        std::memcpy(cookie_out, md, COOKIE_LEN);
    }

    static inline bool verify(const uint8_t secret[32], uint32_t client_ip, uint16_t client_port, uint64_t now_sec, const uint8_t cookie_in[16]) noexcept {
        uint8_t expected[COOKIE_LEN];
        generate(secret, client_ip, client_port, now_sec, expected);
        if (CRYPTO_memcmp(cookie_in, expected, COOKIE_LEN) == 0) return true;

        if (now_sec >= 20) {
            generate(secret, client_ip, client_port, now_sec - 20, expected);
            if (CRYPTO_memcmp(cookie_in, expected, COOKIE_LEN) == 0) return true;
        }
        return false;
    }
};

class HandshakeClient {
public:
    // FIX CRIT-1/CRIT-2: Takes master_key (per-user secret derived from token)
    // for HMAC authentication, NOT server_pubkey (which is public knowledge and
    // provides zero authentication — any attacker who knows the pubkey could
    // forge a valid HANDSHAKE_INIT without the token).
    HandshakeClient(const uint8_t key_id[8], const uint8_t master_key[32]);
    ~HandshakeClient();

    std::vector<uint8_t> build_init();
    // Audit issue 3.1: process_resp expects 80-byte response (48 header + 16 ciphertext + 16 tag).
    // Authenticates that HANDSHAKE_RESP was generated by server with MasterKey,
    // and verifies AEAD tag with transcript AAD to defeat active MITM attacks.
    bool process_resp(const uint8_t* resp, size_t len, SessionKeys& out);

private:
    uint8_t m_key_id[8];
    uint8_t m_master_key[32]; // FIX CRIT-1: was m_server_pubkey (public, not a secret)
    EVP_PKEY* m_ephemeral_pkey;
};

struct HandshakeSeenKey {
    uint64_t key_id{0};
    uint64_t timestamp{0};

    bool operator==(const HandshakeSeenKey& other) const noexcept {
        return key_id == other.key_id && timestamp == other.timestamp;
    }
    bool operator!=(const HandshakeSeenKey& other) const noexcept {
        return !(*this == other);
    }
};

struct HandshakeSeenKeyHash {
    size_t operator()(const HandshakeSeenKey& k) const noexcept {
        uint64_t h = k.key_id ^ (k.timestamp + 0x9e3779b97f4a7c15ULL + (k.key_id << 6) + (k.key_id >> 2));
        return static_cast<size_t>(h);
    }
};

class HandshakeServer {
public:
    // FIX CRIT-1: Now takes master_key_map (key_id → 32-byte master key) so that
    // process_init can verify MAC using the user's secret, not the server pubkey.
    HandshakeServer(const std::unordered_map<uint64_t, std::string>& user_map,
                    const std::unordered_map<uint64_t, std::vector<uint8_t>>& master_key_map);
    ~HandshakeServer();

    bool process_init(const uint8_t* init, size_t len, uint64_t& key_id_out);
    // FIX CRIT-3: build_resp now returns 80-byte response (was 64)
    std::vector<uint8_t> build_resp(uint64_t key_id, uint32_t assigned_ip, uint16_t mtu, SessionKeys& out);
    std::vector<uint8_t> get_pubkey() const;

private:
    std::unordered_map<uint64_t, std::string> m_user_map;
    std::unordered_map<uint64_t, std::vector<uint8_t>> m_master_keys; // FIX CRIT-1
    EVP_PKEY* m_static_pkey;

    std::mutex m_mutex;
    // FIX Audit: Map timestamp -> received_time_ms.
    // Previously, prune_timestamps() called m_seen_timestamps.clear() every 60s,
    // which created a vulnerability window where replayed HANDSHAKE_INIT packets
    // within the 30-second window were accepted again after the wipe.
    std::unordered_map<HandshakeSeenKey, uint64_t, HandshakeSeenKeyHash> m_seen_timestamps;
    std::deque<std::pair<HandshakeSeenKey, uint64_t>> m_seen_order; // O(1) time-ordered queue
    uint64_t m_last_prune_time;

    struct ClientState {
        EVP_PKEY* client_ephemeral_pkey;
        uint64_t timestamp;
    };
    std::unordered_map<uint64_t, ClientState> m_pending_clients;
    std::deque<std::pair<uint64_t, uint64_t>> m_pending_order; // O(1) pending client queue

    void load_or_generate_key();
    void prune_timestamps(uint64_t now_ms);
    // FIX CRIT-5: Evict stale pending handshake states that exceeded TTL.
    // Without this, m_pending_clients grows unbounded if clients never
    // complete the handshake (e.g. attacker sends INIT but never reads RESP).
    void prune_pending(uint64_t now_ms);
};
