plugins {
    id 'com.android.application'
}

android {
    namespace 'com.aegs.titan'
    compileSdk 34

    defaultConfig {
        applicationId "com.aegs.titan"
        minSdk 24
        targetSdk 34
        versionCode 600
        versionName "6.0-titan"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
